### ISSUE TITLE
enhancement: live update instead of refresh page

### ISSUE THREAD

**Issue by billiegoose** [elingerojo/contexter-cli#3]
Right now the page refreshes and all my opened tree nodes get closed again. The next logical step is to make it a React application that gets a live update from a Websocket server and updates the content without a page refresh!

Ooh, or better yet, we could use the legit "hot module replacement" protocol that webpack and browserify-hmr use! Just have our "context state" exported as a module... I've never learned how hot module replacement works, that would be so much fun.

Assign to me! :)

**Comment by billiegoose** [comment]
Oh bother, I see it's an Angular 1.x application. I've tried to hack on those before (linux-dash and local-npm) but have never learned enough to make sense of them. How long does it take to learn enough Angular 1.x to be dangerous do you think?

**Comment by billiegoose** [comment]
Also where did you get those awesome file folder and JSON explorer components?

**Comment by elingerojo** [comment]
[jsTree](https://www.jstree.com/)

[ng-json-explorer](https://github.com/odra/ng-json-explorer)

**Comment by elingerojo** [comment]
> the page refreshes and all my opened tree nodes get closed again

I used [browser-sync](https://www.npmjs.com/package/browser-sync) because `jus` used it

...but for this application, that has a "fixed" homepage, it will make more sense to use tools for 'dashboard-like' apps

**Comment by elingerojo** [comment]
To make the homepage work, I 'rigged' `routes.js` and added some ['hacky' code](https://github.com/elingerojo/contexter-cli/blob/master/lib/routes.js#L35-L38).

Kind of forced it. Will not mind throwing it away for anything better 😀 

> Eh... don't add too many features to contexter-cli if it's just meant to serve as an example application. 

You're right

...but that made me think that `contexter-cli` could be a tool to develop and test single `plugins`.

It was born to be an example application but could be used to show the capabilities of new plugins. I am thinking like a way to demo them (not the `contexter` itself)

So any work on it could be useful (if it becomes too useful, then it can be forked to a `contexter-dev` 😜  )

Will add CLI `--ignores` ...let's see how it ends...

**Comment by elingerojo** [comment]
Bumped versions on both `contexter` and `contexter-cli`

- Added `--ignore <dir-to-ignore>`, if omitted defaults to `node_modules`
- Added `--all`, forces to watch all files, even files that do not have a corresponding plugin to process them. If omitted, ONLY `datafiles` and `images` are watched/contexted. I understand that this is a change on behavior because it defaults to optimize and "cherry-pick" from directory but IMHO is a better approach and the `--all` flag keeps the old behavior available for applications like `jus` that wants ALL the files "no matter what".

**Comment by elingerojo** [comment]
> live update instead of refresh page

@wmhilton  Done!
Bumped to [version 0.3.0](https://github.com/elingerojo/contexter-cli/commit/6f8f51b6f184f7d2e0789288aa5a90d2acf8b39a)

- Removed browser-sync (...oh! I forgot to remove dependency from package.json  😞 )
- Added [SSE (server side events)](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)
- Changed from Angular to [Vue.js](https://vuejs.org/)

 Pilfered from:
- SSE - [How to Add Simple Real Time Streaming to Your Express App with Server Sent Events](https://www.terlici.com/2015/12/04/realtime-node-expressjs-with-sse.html)
- JSON viewer - [Building a JSON Tree View Component in Vue.js from Scratch in Six Steps](https://devblog.digimondo.io/building-a-json-tree-view-component-in-vue-js-from-scratch-in-six-steps-ce0c05c2fdd8)

**Comment by billiegoose** [comment]
Oh man, keeping up with your progress is gonna be a full-time job. I gotta try this!

**Comment by billiegoose** [comment]
I feel like I should close this, because "enhancement: live update" is Mission Accomplished! (or Achievement Unlocked! or [Insert your favorite fist-pump victory here 💪])

**Comment by elingerojo** [comment]
_"...the eagle has landed"_ ha ha 😄 

I am glad you like it
